<?php 
/*
Template Name: Вируальные туры
*/ ?>

<?php get_header(); ?>

<div class="shooting aeropanoramabg">	
	<div class="container">
		<div class="shooting_block">				
			<div class="shooting__leftbox">
				<h2 class="common-title"><?php the_field('туры_первый_блок_заголовок'); ?></h2>
				<div class="shooting__txtbox">
					<?php the_field('туры_первый_блок_текст'); ?>
				</div>
				<div class="shooting__button">
					<?php the_field('туры_первый_блок_ссылка'); ?>
				</div>
			</div>
			<div class="shooting__rightbox">
				<div class="common-slider">
					<div class="slider-owl-carousel">						
						<?php $gal_id = get_field('туры_первый_блок_id_галереи'); ?>
						<?php echo do_shortcode('[nggallery id="'.$gal_id.'" template="more_gallery3"]'); ?>
					</div>
					<div class="common-slider__txtbox">
						<div class="common-slider__numberbox">
							<span class="number-active">1</span>
							<i>/</i>
							<span class="number-all">9</span>
						</div>
						
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="panorams">
	<div class="container">
		<h2 class="common-title panorams__caption">Панорамы</h2>
		<ul class="panorams__tabs">
			<li><a href="panoramstab1" class="panorams__acivetab">Земельный участок</a></li>
			<!-- <li><a href="panoramstab2">Загородный дом</a></li>
			<li><a href="panoramstab3">Жилой комплекс</a></li>
			<li><a href="panoramstab4">Инфраструктура</a></li> -->
		</ul>
		<div class="clearfix"></div>                    		
		<div class="panorams__content" >
			
			
			<div class="panorams__img panoramstab1" id="panoDIV">
			
			<noscript>

					<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="100%" height="100%" id="/zavoddata/zavod">
						<param name="movie" value="/zavoddata/zavod.swf"/>
						<param name="allowFullScreen" value="true"/>
						<!--[if !IE]>-->
						<object type="application/x-shockwave-flash" data="zavoddata/zavod.swf" width="100%" height="100%">
							<param name="movie" value="/zavoddata/zavod.swf"/>
							<param name="allowFullScreen" value="true"/>
							<!--<![endif]-->
							<a href="http://www.adobe.com/go/getflash">
								<img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player to visualize the Virtual Tour : New Project (Virtual tour generated by Panotour)"/>
							</a>
						<!--[if !IE]>-->
						</object>
						<!--<![endif]-->
					</object>

				</noscript>
			</div>
			<div class="panorams__img panoramstab2" id="panoDIV2">
			<noscript>

					<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="100%" height="100%" id="/zavoddata/zavod">
						<param name="movie" value="/zavoddata/zavod.swf"/>
						<param name="allowFullScreen" value="true"/>
						<!--[if !IE]>-->
						<object type="application/x-shockwave-flash" data="zavoddata/zavod.swf" width="100%" height="100%">
							<param name="movie" value="/zavoddata/zavod.swf"/>
							<param name="allowFullScreen" value="true"/>
							<!--<![endif]-->
							<a href="http://www.adobe.com/go/getflash">
								<img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player to visualize the Virtual Tour : New Project (Virtual tour generated by Panotour)"/>
							</a>
						<!--[if !IE]>-->
						</object>
						<!--<![endif]-->
					</object>

				</noscript>				
			</div>
			<div class="panorams__img panoramstab3" id="panoDIV3">
				<noscript>

					<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="100%" height="100%" id="/zavoddata/zavod">
						<param name="movie" value="/zavoddata/zavod.swf"/>
						<param name="allowFullScreen" value="true"/>
						<!--[if !IE]>-->
						<object type="application/x-shockwave-flash" data="zavoddata/zavod.swf" width="100%" height="100%">
							<param name="movie" value="/zavoddata/zavod.swf"/>
							<param name="allowFullScreen" value="true"/>
							<!--<![endif]-->
							<a href="http://www.adobe.com/go/getflash">
								<img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player to visualize the Virtual Tour : New Project (Virtual tour generated by Panotour)"/>
							</a>
						<!--[if !IE]>-->
						</object>
						<!--<![endif]-->
					</object>

				</noscript>				
			</div>
			<div class="panorams__img panoramstab4" id="panoDIV4">
				<noscript>

					<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="100%" height="100%" id="/zavoddata/zavod">
						<param name="movie" value="/zavoddata/zavod.swf"/>
						<param name="allowFullScreen" value="true"/>
						<!--[if !IE]>-->
						<object type="application/x-shockwave-flash" data="zavoddata/zavod.swf" width="100%" height="100%">
							<param name="movie" value="/zavoddata/zavod.swf"/>
							<param name="allowFullScreen" value="true"/>
							<!--<![endif]-->
							<a href="http://www.adobe.com/go/getflash">
								<img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player to visualize the Virtual Tour : New Project (Virtual tour generated by Panotour)"/>
							</a>
						<!--[if !IE]>-->
						</object>
						<!--<![endif]-->
					</object>

				</noscript>			
			</div>
		</div>
	</div>
</div>	

<div class="pricedays">
	<div class="container">
		<h2 class="common-title">Стоимость и сроки выполнения </h2>
		<div class="pricedays__block">
			<div class="pricedays__box">
				<div class="pricedays__txtbox">
					<span class="pricedays__toptxt"><?php the_field('заголовок_первого_пунтка'); ?></span>
					<span class="pricedays__pricetxt">от <b><?php the_field('цена_первого_пункта'); ?></b><i class="fa fa-rub" aria-hidden="true"></i></span>	
				</div>	
				<div class="pricedays__button">
					<?php the_field('ссылка_первого_пункта'); ?>
				</div>				
			</div>		
			<div class="pricedays__box">
				<div class="pricedays__txtbox">
					<span class="pricedays__toptxt"><?php the_field('заголовок_второго_пункта'); ?></span>
					<span class="pricedays__pricetxt">от <b><?php the_field('цена_второго_пункта'); ?></b><i class="fa fa-rub" aria-hidden="true"></i></span>	
					
				</div>
				<div class="pricedays__button">
					<?php the_field('ссылка_второго_пункта'); ?>
				</div>				
			</div>	
			<div class="pricedays__box">
				<div class="pricedays__txtbox">
					<span class="pricedays__toptxt"><?php the_field('заголовок_третьего_пункта'); ?></span>
					<span class="pricedays__pricetxt">от <b><?php the_field('цена_третьего_пункта'); ?> </b><i class="fa fa-rub" aria-hidden="true"></i></span>	
				</div>
				<div class="pricedays__button">
					<?php the_field('ссылка_третьего_пункта'); ?>
				</div>				
			</div>					
		</div>
		<p class="pricedays__bottomtext">*от 2 и более объектов и сотрудничество на постоянной основе обсуждается индивидуально. </p>
	</div>
</div>

<div class="servicetxt">
	<div class="container">
		<?php the_field('туры_seoтекст'); ?>
	</div>
</div>
<script type="text/javascript" src="/zavoddata/zavod.js"></script>
<script type="text/javascript">
	if (isVRModeRequested()){
		accessWebVr();
	}else{
		accessStdVr();
	}
</script>
<?php get_footer(); ?>
